# Generated by Django 5.2 on 2025-10-17 05:17

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ContactMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("subject", models.CharField(max_length=200)),
                ("message", models.TextField()),
                ("is_read", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Contact Message",
                "verbose_name_plural": "Contact Messages",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CoreExpertise",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                (
                    "icon_name",
                    models.CharField(
                        help_text="Icon identifier (e.g., 'code', 'palette', 'layers')",
                        max_length=50,
                    ),
                ),
                ("order", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Core Expertise",
                "verbose_name_plural": "Core Expertise",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="Education",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("degree", models.CharField(max_length=200)),
                ("institution", models.CharField(max_length=200)),
                ("year", models.IntegerField()),
                ("description", models.TextField(blank=True)),
                (
                    "icon_name",
                    models.CharField(
                        default="graduation-cap",
                        help_text="Icon identifier",
                        max_length=50,
                    ),
                ),
                ("order", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Education",
                "verbose_name_plural": "Education",
                "ordering": ["-year", "order"],
            },
        ),
        migrations.CreateModel(
            name="Experience",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("company", models.CharField(max_length=200)),
                ("start_date", models.DateField()),
                (
                    "end_date",
                    models.DateField(
                        blank=True,
                        help_text="Leave empty for current position",
                        null=True,
                    ),
                ),
                ("description", models.TextField()),
                (
                    "technologies",
                    models.CharField(
                        help_text="Comma-separated list of technologies/skills",
                        max_length=500,
                    ),
                ),
                ("order", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Experience",
                "verbose_name_plural": "Experience",
                "ordering": ["-start_date", "order"],
            },
        ),
        migrations.CreateModel(
            name="NewsletterSubscriber",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("is_active", models.BooleanField(default=True)),
                ("subscribed_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Newsletter Subscriber",
                "verbose_name_plural": "Newsletter Subscribers",
                "ordering": ["-subscribed_at"],
            },
        ),
        migrations.CreateModel(
            name="PersonalInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="John Doe", max_length=100)),
                (
                    "title",
                    models.CharField(default="Senior Product Designer", max_length=200),
                ),
                (
                    "tagline",
                    models.CharField(
                        default="Crafting Digital Excellence", max_length=500
                    ),
                ),
                (
                    "hero_description",
                    models.TextField(
                        default="I transform complex problems into elegant, user-centered solutions that drive business growth and delight users at every touchpoint."
                    ),
                ),
                (
                    "about_heading",
                    models.CharField(
                        default="Building Digital Experiences That Matter",
                        max_length=200,
                    ),
                ),
                (
                    "about_description",
                    models.TextField(
                        default="Passionate about creating meaningful digital experiences"
                    ),
                ),
                (
                    "about_detail",
                    models.TextField(
                        default="With over 5 years of experience in digital design and development, I've had the privilege of working with startups and established companies to create products that users love and businesses depend on."
                    ),
                ),
                (
                    "email",
                    models.EmailField(default="hello@johndoe.com", max_length=254),
                ),
                ("phone", models.CharField(default="+1 (234) 567-890", max_length=20)),
                (
                    "location",
                    models.CharField(default="San Francisco, CA (PST)", max_length=100),
                ),
                (
                    "availability_status",
                    models.CharField(
                        default="Currently available for freelance projects",
                        max_length=100,
                    ),
                ),
                ("years_experience", models.IntegerField(default=5)),
                ("projects_completed", models.IntegerField(default=50)),
                ("awards_won", models.IntegerField(default=15)),
                ("happy_clients", models.IntegerField(default=30)),
                ("linkedin_url", models.URLField(blank=True, null=True)),
                ("github_url", models.URLField(blank=True, null=True)),
                ("twitter_url", models.URLField(blank=True, null=True)),
                ("dribbble_url", models.URLField(blank=True, null=True)),
                (
                    "resume_pdf",
                    models.FileField(blank=True, null=True, upload_to="resume/"),
                ),
                (
                    "footer_tagline",
                    models.CharField(
                        default="Crafting digital experiences with precision, passion, and purpose.",
                        max_length=200,
                    ),
                ),
                (
                    "copyright_text",
                    models.CharField(
                        default="© 2025 John Doe. All rights reserved.", max_length=200
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Personal Information",
                "verbose_name_plural": "Personal Information",
            },
        ),
        migrations.CreateModel(
            name="ProjectCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("slug", models.SlugField(blank=True, unique=True)),
                ("order", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Project Category",
                "verbose_name_plural": "Project Categories",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="SiteSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "site_title",
                    models.CharField(default="John Doe Portfolio", max_length=200),
                ),
                (
                    "site_description",
                    models.TextField(
                        default="Portfolio website showcasing my work and skills"
                    ),
                ),
                (
                    "favicon",
                    models.ImageField(blank=True, null=True, upload_to="site/"),
                ),
                ("logo", models.ImageField(blank=True, null=True, upload_to="site/")),
                ("meta_keywords", models.CharField(blank=True, max_length=500)),
                ("google_analytics_id", models.CharField(blank=True, max_length=50)),
                (
                    "primary_color",
                    models.CharField(
                        default="#D4AF37", help_text="Hex color code", max_length=7
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Site Settings",
                "verbose_name_plural": "Site Settings",
            },
        ),
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("frontend", "Frontend"),
                            ("backend", "Backend"),
                            ("design", "Design"),
                            ("mobile", "Mobile"),
                            ("uiux", "UI/UX"),
                            ("tools", "Tools"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "proficiency",
                    models.IntegerField(
                        help_text="Proficiency level from 1 to 5",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                (
                    "icon_name",
                    models.CharField(
                        blank=True,
                        help_text="Icon identifier for the skill",
                        max_length=50,
                    ),
                ),
                ("order", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Skill",
                "verbose_name_plural": "Skills",
                "ordering": ["category", "order"],
            },
        ),
        migrations.CreateModel(
            name="Testimonial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("client_name", models.CharField(max_length=100)),
                ("client_position", models.CharField(max_length=200)),
                ("client_company", models.CharField(max_length=200)),
                (
                    "client_photo",
                    models.ImageField(blank=True, null=True, upload_to="testimonials/"),
                ),
                ("testimonial", models.TextField()),
                (
                    "rating",
                    models.IntegerField(
                        default=5,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                ("order", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Testimonial",
                "verbose_name_plural": "Testimonials",
                "ordering": ["order", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Timeline",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.IntegerField()),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("order", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Timeline",
                "verbose_name_plural": "Timeline",
                "ordering": ["-year", "order"],
            },
        ),
        migrations.CreateModel(
            name="Tool",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("order", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Tool",
                "verbose_name_plural": "Tools",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="Achievement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.TextField()),
                ("order", models.IntegerField(default=0)),
                (
                    "experience",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="achievements",
                        to="core.experience",
                    ),
                ),
            ],
            options={
                "verbose_name": "Achievement",
                "verbose_name_plural": "Achievements",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("slug", models.SlugField(blank=True, unique=True)),
                ("short_description", models.CharField(max_length=300)),
                ("full_description", models.TextField(blank=True)),
                ("thumbnail", models.ImageField(upload_to="projects/thumbnails/")),
                (
                    "featured_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="projects/featured/"
                    ),
                ),
                (
                    "technologies",
                    models.CharField(
                        help_text="Comma-separated list of technologies (e.g., React, Node.js, Tailwind)",
                        max_length=500,
                    ),
                ),
                ("live_url", models.URLField(blank=True, null=True)),
                ("github_url", models.URLField(blank=True, null=True)),
                ("case_study_url", models.URLField(blank=True, null=True)),
                ("is_featured", models.BooleanField(default=False)),
                ("order", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="projects",
                        to="core.projectcategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "Project",
                "verbose_name_plural": "Projects",
                "ordering": ["order", "-created_at"],
            },
        ),
    ]
